// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjycxyasxeupwxckplsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqeWN4eWFzeGV1cHd4Y2twbHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NTIwMjAsImV4cCI6MjA2MDUyODAyMH0.jx5kbcLFUolFe0w4_IssjfZ32i-fHHksEjaMiTVrQSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);